//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryDataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int Id { get; set; }
        public string requestTitle { get; set; }
        public string requestBody { get; set; }
        public string status { get; set; }
        public int role { get; set; }
    }
}
